#!/bin/sh
# wg - tiny, unix-y static site generator

IDIR="$(echo "$1" | sed -e 's,/*$,,')"
if [ -z "$IDIR" ] || [ ! -d "$IDIR" ]; then
	echo "Usage: $(basename $0) [dir]"
	exit 1
fi

if [ -f "$IDIR/_/wg.conf" ]; then
	. "$IDIR/_/wg.conf"
fi

CDIR="$PWD"
ODIR="$CDIR/$(basename $IDIR).static"
rm -rf "$ODIR"
mkdir -p "$ODIR"

cd "$IDIR"
FILES=$(find . -name "_*" -prune -o ! -iname ".*" -type f -print | sed -e 's|^\./||')
for f in $FILES; do
	name=${f%.*}
	ext=${f##*.}
	if [ -f "./_/ft/$ext" ]; then
		outext=$(GET_EXT=1 ./_/ft/$ext)
		: ${outext:="html"}
		echo "* $f -> $name.$outext"
		PAGE="$name" ./_/ft/$ext $f > "$ODIR/$name.$outext"
	else
		echo "* $f"
		cp "$f" "$ODIR/$f"
	fi
done
